# Stubs for py4j.tests.py4j_callback_example2 (Python 3.6)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from typing import Any

class ClassNone:
    def getName(self): ...
    class Java:
        implements: Any = ...
