# Stubs for py4j.tests.py4j_callback_example (Python 3.6)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from typing import Any, Optional

class Addition:
    def doOperation(self, i: Any, j: Any, k: Optional[Any] = ...): ...
    class Java:
        implements: Any = ...
