# Stubs for pandas.io.sas.sasreader (Python 3.6)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from typing import Any, Optional

def read_sas(filepath_or_buffer: Any, format: Optional[Any] = ..., index: Optional[Any] = ..., encoding: Optional[Any] = ..., chunksize: Optional[Any] = ..., iterator: bool = ...): ...
