# Stubs for pandas.core.api (Python 3.6)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from typing import Any

class TimeGrouper:
    def __new__(cls, *args: Any, **kwargs: Any): ...
