# Stubs for pandas.io.clipboard (Python 3.6)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from typing import Any

copy: Any
paste: Any
clipboard_get = paste
clipboard_set = copy
