# Stubs for pandas.io.clipboards (Python 3.6)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from typing import Any, Optional

def read_clipboard(sep: str = ..., **kwargs: Any): ...
def to_clipboard(obj: Any, excel: bool = ..., sep: Optional[Any] = ..., **kwargs: Any): ...
