# Stubs for pandas.io.feather_format (Python 3.6)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from typing import Any

def to_feather(df: Any, path: Any) -> None: ...
def read_feather(path: Any, use_threads: bool = ...): ...
