# Stubs for pandas.io.gcs (Python 3.6)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from typing import Any, Optional

def get_filepath_or_buffer(filepath_or_buffer: Any, encoding: Optional[Any] = ..., compression: Optional[Any] = ..., mode: Optional[Any] = ...): ...
